### ISSUE TITLE
No control over runloop modes

### ISSUE THREAD

**Issue by DavidPhillipOster** [Mijick/Timer#3]
The code as I write this, creates the internalTimer with [scheduledTimer()](https://github.com/Mijick/Timer/blob/main/Sources/Internal/MTimer.swift#L91).  on macOS, that means the timer won't run when the mouse is down in a menu item or other tracking loop. Instead, create the timer unscheduled, and schedule it on the runloop with the correct mode. See NSRunLoop's add(timer: mode:)

At least there should be a comment warning programmers of the problem.

**Comment by FulcrumOne** [comment]
Thank you very much for this comment, I wasn't aware of this problem. I'll fix it this weekend.
